#!/bin/sh

xrdb -merge ~/.Xresources
[ -f "$HOME/.xprofile" ] && . ~/.xprofile
#xrdb -merge ~/.Xresources
wal -n -i ~/.config/wall.png -b '#000000'
while true; do
    # Log stderror to a file
    #dwm 2> ~/.dwm.log
    # No error logging
    dwm >/dev/null 2>&1
done
#exec i3
#exec bspwm
