#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -o '%(upload_date)s-%(title)s.%(ext)s' -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	sage="sage -q"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"\
	q="exit"\
	dunstpause="notify-send 'dunst' 'Pausing dunst...'; sleep 2;  notify-send 'DUNST_COMMAND_PAUSE'"\
	dunstresume="notify-send 'dunst' 'Resuming dunst...' && notify-send 'DUNST_COMMAND_RESUME'"\
	glog="git log --all --graph --decorate"\
	clog="config log --all --graph --decorate"\
	cam="mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0"\
	createvocabhtml="awk -F '\t' '{print \"<div class='word'><b>\"$2\"</b></div><div class='part_of_speech'>\"$4\"</div>\t <div class='meaning'><b>\"$3\"</b></div><div class='explanation'>\"$5\"</div><div class='example'>\"$6\"</div><div class='bottom'>no. \"$1\", \"$7\", \"$8\"</div>\"}'"


# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"\
	cast="mkchromecast --video --control -i"\
	castaudio="mkchromecast --control --screencast"\
	rest="clear && sleep 90 && echo ###########START############"
	#gpg="gpg --homedir=$GNUPGHOME"

# Some useful functions
vf() { fzf | xargs -r -I % $EDITOR % ;}
#	 [ -z $video ] || ( mpv "$video" & disown ) ;}
vpdf() { pdf="$( ls -t $HOME/.cache/luakit/viewpdf/ | fzf -e )"
	[ -z $pdf ] || ( $READER "$HOME/.cache/luakit/viewpdf/$pdf" & disown ) ;}
epdf() { pdf="$(du -a --time ETH/ | awk '!($1="")' | sort -r | grep '\.pdf' | awk '!($1="")' | awk '!($1="")' | sed 's/^ //' | fzf -e )"
	[ -z $pdf ] || ( $READER "$pdf" & ) ;}
alias config='/usr/bin/git --git-dir=/home/alex/.local/share/git_dotfiles --work-tree=/home/alex'
