#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources	# Uncomment to use Xresources colors/settings on startup
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
#wal -i ${XDG_CONFIG_HOME:-$HOME/.config}/wall.png -b '#000000'
xcompmgr &		# xcompmgr for transparency (and apparently to reduce tearing)
dunst &			# dunst for notifications
dwmblocks 2> /dev/null &
xset r rate 300 50 &	# Speed xrate up
unclutter --timeout 2 --ignore-scrolling &		# Remove mouse when idle
insync start &
element-desktop --hidden &
transmission-daemon &
echo "$HOME/.config/mpd/state" | entr -np pkill -RTMIN+11 dwmblocks &
xrandr --listactivemonitors | grep -q '1920.*x1080.*HDMI-1$' && ( xrandr --output  HDMI-1 --scale 1.5 && setbg ) # set scale for 2nd monitor if connected
redshift &		# Bluefilter based on time
keynav &		# emulate mouse clicks with vim-bindings and starting with Ctrl+;
